# Generated by Django 4.2.14 on 2024-08-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_excerpt_alter_post_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
